# Generated by Django 4.1.3 on 2023-01-17 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='catogeries')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagemprimeira', models.ImageField(default=False, upload_to='paginas')),
                ('imagemsegunda', models.ImageField(default=False, upload_to='paginas1')),
                ('imagemterceira', models.ImageField(default=False, upload_to='paginas2')),
                ('imagemquarta', models.ImageField(default=False, upload_to='paginas3')),
                ('status', models.TextField(choices=[('inativo', 'INATIVO'), ('ativo', 'ATIVO')], default='INATIVO', max_length=10)),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.categories', verbose_name='Categorias')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('-create',),
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imagem', models.FileField(upload_to='catalogos/pdf')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='catalogos/capa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ('-id',),
            },
        ),
    ]
