# Generated by Django 4.1.3 on 2022-11-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_categories_products_delete_bannerimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='imagem',
        ),
        migrations.AddField(
            model_name='products',
            name='imagemprimeira',
            field=models.ImageField(default=False, upload_to='paginas'),
        ),
        migrations.AddField(
            model_name='products',
            name='imagemquarta',
            field=models.ImageField(default=False, upload_to='paginas'),
        ),
        migrations.AddField(
            model_name='products',
            name='imagemsegunda',
            field=models.ImageField(default=False, upload_to='paginas'),
        ),
        migrations.AddField(
            model_name='products',
            name='imagemterceira',
            field=models.ImageField(default=False, upload_to='paginas'),
        ),
    ]
