# Generated by Django 4.1.3 on 2022-11-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_remove_products_imagem_products_imagemprimeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='products',
            name='imagemquarta',
            field=models.ImageField(default=False, upload_to='paginas3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='imagemsegunda',
            field=models.ImageField(default=False, upload_to='paginas1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='imagemterceira',
            field=models.ImageField(default=False, upload_to='paginas2'),
        ),
    ]
