# Generated by Django 4.1.3 on 2022-11-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='catalogo',
            new_name='imagem',
        ),
    ]
