# Generated by Django 4.1.3 on 2022-11-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_rename_catalogo_materials_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='cover',
            field=models.ImageField(default=2, upload_to='catalogos/capa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materials',
            name='imagem',
            field=models.FileField(upload_to='catalogos/pdf'),
        ),
    ]
