# Generated by Django 4.1.3 on 2022-11-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_materials_cover_alter_materials_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='materials',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='catalogos/capa'),
        ),
    ]
