# Generated by Django 4.1.3 on 2022-11-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_alter_materials_options_alter_materials_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('-id',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='materials',
            options={'ordering': ('-id',), 'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-create',), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.TextField(choices=[('inativo', 'inativo'), ('ativo', 'ativo')], default='INATIVO', max_length=10),
        ),
    ]
