# Generated by Django 4.1.3 on 2022-11-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_alter_categories_options_alter_materials_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.TextField(choices=[('inativo', 'INATIVO'), ('ativo', 'ATIVO')], default='INATIVO', max_length=10),
        ),
    ]
