# Generated by Django 4.1.3 on 2022-11-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sample',
            field=models.BooleanField(default=False, verbose_name='Destaque?'),
        ),
    ]
